import React from 'react';
import { Shield, FileText, AlertTriangle, ArrowLeft } from 'lucide-react';

interface Props {
  page: 'terms' | 'privacy' | 'risk';
  onBack: () => void;
}

export default function LegalPage({ page, onBack }: Props) {
  
  const renderContent = () => {
    switch (page) {
      case 'terms':
        return (
          <div className="space-y-4">
            <h3 className="text-xl font-bold text-white">Terms of Service</h3>
            <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>
            <p>Welcome to CNP Direct. By accessing our "Sentinel OS" platform, you agree to these terms.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>License:</strong> We grant you a limited, non-exclusive license to use the software for personal analysis.</li>
              <li><strong>Payments:</strong> Subscriptions are billed in advance. You may cancel at any time via the Stripe portal.</li>
              <li><strong>No Refunds:</strong> Due to the nature of digital goods, we generally do not offer refunds after the 7-day trial period.</li>
              <li><strong>Termination:</strong> We reserve the right to terminate accounts that abuse the API or share credentials.</li>
            </ul>
          </div>
        );
      case 'privacy':
        return (
          <div className="space-y-4">
            <h3 className="text-xl font-bold text-white">Privacy Policy</h3>
            <p>We value your privacy. We do not sell your data to third-party hedge funds.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Data Collection:</strong> We collect your email and usage data to improve the AI models.</li>
              <li><strong>Payment Data:</strong> Your credit card info is processed securely by Stripe. We never see your full card number.</li>
              <li><strong>Cookies:</strong> We use secure session cookies to keep you logged in.</li>
            </ul>
          </div>
        );
      case 'risk':
        return (
          <div className="space-y-4 border-l-4 border-amber-500 pl-4">
            <h3 className="text-xl font-bold text-amber-500 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5" /> Risk Disclosure
            </h3>
            <p className="font-bold text-white">CNP DIRECT IS NOT A REGISTERED INVESTMENT ADVISOR.</p>
            <p>Trading stocks and options involves a high degree of risk and is not suitable for all investors. You could lose some or all of your initial investment.</p>
            <ul className="list-disc pl-5 space-y-2 text-slate-300">
              <li>The signals provided by "The Oracle" and "The Strategist" are generated by AI algorithms based on historical data.</li>
              <li><strong>Past performance is not indicative of future results.</strong></li>
              <li>You are solely responsible for your own trading decisions. Do not trade with money you cannot afford to lose.</li>
            </ul>
          </div>
        );
    }
  };

  return (
    <div className="max-w-3xl mx-auto py-8 animate-in fade-in slide-in-from-bottom-4">
      <button 
        onClick={onBack}
        className="flex items-center gap-2 text-slate-400 hover:text-white mb-6 transition-colors"
        data-testid="button-back-legal"
      >
        <ArrowLeft className="h-4 w-4" /> Back to Terminal
      </button>
      
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 text-slate-400 leading-relaxed shadow-xl">
        {renderContent()}
      </div>
    </div>
  );
}
